### ISSUE TITLE
Can't Deploy Template because nodejs 10 has been depricated

### ISSUE THREAD

**Issue by konaitor** [alexa/skill-sample-nodejs-trivia#111]
When trying to deploy this and other repository apps, cloudformation fails with this error: 

Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs14.x) while creating or updating functions.

Can this be updated for the newer runtime?

**Comment by aszk** [comment]
We have updated the template. Thank you for your feedback.
