### ISSUE TITLE
Unable to create Lambda function successfully

### ISSUE THREAD

**Issue by wongshar** [alexa/skill-sample-nodejs-trivia#113]
Hello, I have a question for **Step 2. Lambda Function, Step 9. Wait for the status of all resources to change to CREATE_COMPLETE.**

After I hit the Deploy button from Step 8, I have been getting Create failed message for the alexaskillskitnodejstriviaskill function (please see below attachment). I cleared the stack and tried multiple times but have not succeeded. I'm not sure how to solve this issue and wonder if anyone can help. (Note: AWS has changed Serverless Application Repository under **applications**, not under **functions** anymore)

Thank you!

![Screen Shot 2023-01-08 at 11 14 17 PM](https://user-images.githubusercontent.com/122257350/211258258-e11ee27b-04e6-4e9e-8374-6c4175865a91.png)
![Screen Shot 2023-01-08 at 11 11 06 PM](https://user-images.githubusercontent.com/122257350/211258260-087e98ca-876b-4984-b3c1-bc83c2bec2b5.png)

**Comment by aszk** [comment]
We have updated the template. Thank you for your feedback.
