### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by elecay** [alexa/skill-sample-nodejs-trivia#12]
Links to videos are broken:

For guidance on designing a voice experience with Alexa you can also watch **this video**.

For more background information on using the Alexa Skills Kit please **watch this**

**Comment by JennJin** [comment]
@akersh-s - Links in the https://github.com/alexa/skill-sample-nodejs-trivia/blob/en-US/instructions/0-intro.md for the Videos need to be updated.

**Comment by janacm** [comment]
This link is also broken:

![image](https://user-images.githubusercontent.com/2055312/33343008-edd18eac-d451-11e7-85c1-a399f7c186a8.png)

**Comment by BrunoAssis** [comment]
In [instructions/2-lambda-function.md](https://github.com/alexa/skill-sample-nodejs-trivia/blob/en-US/instructions/2-lambda-function.md), step 12, the link ("If you want to secure this Lambda function follow the instructions found **here**") is also broken.

**Comment by akersh-s** [comment]
Fixed in PR#95. closing.
