### ISSUE TITLE
Issues with skill endpoint validation

### ISSUE THREAD

**Issue by brianchou121** [alexa/skill-sample-nodejs-trivia#16]
Amazon Certifiers said that "Future versions of the Alexa Skills Kit may add new properties to the JSON request and response formats, while maintaining backward compatibility for the existing properties.  When we invoke the skill with additional parameters, the skill is rejecting it when we expect this to be accepted.  Your code must be resilient to these types of changes. For example, your code for de-serializing a JSON request must not break when it encounters a new, unknown property." Any ideas on what is wrong?

**Comment by JennJin** [comment]
This isn't an issue the Trivia Sample code.
Sounds like you're not using Lambda to host the Skill code and your own endpoint.
[Host a Custom Skill as a Web Service](https://developer.amazon.com/docs/custom-skills/host-a-custom-skill-as-a-web-service.html)
 
Search the [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) for similar issues or post your issue there.
