### ISSUE TITLE
Possible Strict Violation

### ISSUE THREAD

**Issue by bramscho** [alexa/skill-sample-nodejs-trivia#17]
![screen shot 2017-07-12 at 7 33 55 pm](https://user-images.githubusercontent.com/17304021/28148053-4e389cf8-6739-11e7-8723-99c5cc8f4717.png)

**Comment by bramscho** [comment]
In the code editor on Amazon on lines 234-286, it is giving me these little warnings that say that there is a "possible strict violation". What does this mean and how can I get rid of it? Thanks

**Comment by akersh-s** [comment]
Code's been linted. This shouldn't be a problem anymore. Closing this issue.
