### ISSUE TITLE
How to run the skill locally with node?

### ISSUE THREAD

**Issue by vikash20186** [alexa/skill-sample-nodejs-trivia#19]
Hi,

How to run and test the skill locally with node without loading the source to the Amazon lambda ?

Thanks,
Vikash

**Comment by deepeshdkpathak** [comment]
Please answer the same

**Comment by shnnxn** [comment]
you can use ngrok for it ..
steps are simple
run your code ... 
then run ngrok on different terminal . ngrok will give you a https endpoint , use this endpoint in skill configuration.

**Comment by deepeshdkpathak** [comment]
Sorry, but did't get completely, can his not possible for making curl request to alexa sdk source, as i wish to use apcahe instead of ngrok

**Comment by shnnxn** [comment]
@deepeshdkpathak 
am not sure about that , its just the  endpoint if you can use custom one i dont think there will be any problem.  but i used ngrok for development process it makes easier to debug where there is any connection error . it displays the error so you can work around it .  if you follow my advice then go with ngrok . its way easy , than setting ur own custom endpoint

**Comment by deepeshdkpathak** [comment]
@shnnxn thanks for the advise, I believe to use it by apache, could you please help me request format that we have to call to alexa sdk's index.js handler functions and receive the response.

**Comment by shnnxn** [comment]
@deepeshdkpathak  
sorry i dont have much experiance with apache . i cant help you with  that ..

**Comment by deepeshdkpathak** [comment]
@shnnxn could you please share url format with get/post data for alexa sdk.

**Comment by JennJin** [comment]
Hey Guys, this question would be better asked on the [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html). 
Please shift the discussion there.

**Comment by muneebaahmad** [comment]
After hours of research, I was finally able to test my alexa skill locally. I thought it would be a good idea to put all the instructions in one place. So here you go:

[How to test alexa skill locally](https://medium.com/@moonahmad/how-to-test-alexa-locally-6d498e307a8)
