### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by deepeshdkpathak** [alexa/skill-sample-nodejs-trivia#22]
Hi , Could you please let me explain how we can get questions from api. As following is not working

var request = require('sync-request');
    var requestResponse=request('GET',APIPATH);
    var requestBodyResponse=requestResponse.body.toString('utf-8');
    
    var apiJsonResponse = JSON.parse(requestBodyResponse);
    questions=apiJsonResponse.data;

**Comment by akersh-s** [comment]
recommendation is to post in our forums: https://forums.developer.amazon.com/ since this isn't an issue with the repo itself. closing the issue.
