### ISSUE TITLE
Echosim

### ISSUE THREAD

**Issue by D063520** [alexa/skill-sample-nodejs-trivia#24]
Hello,

we followed the tutorial and in the test console it seams to work. But when we go to Echosim we can open "American Reindeer Trivia" but we cannot make a dialog with it, i.e. we cannot answer the questions. Any ideas?

**Comment by JennJin** [comment]
It doesn't sound like an issue with the Trivia Sample code.

[Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) would be the best source for general troubleshooting help. If you're still having issues, please post there.
