### ISSUE TITLE
answers with numbers only without text

### ISSUE THREAD

**Issue by georpan** [alexa/skill-sample-nodejs-trivia#26]
I have a problem at the answers. There are only numbers without other text...
It doesn't work...

**Comment by georpan** [comment]
At the questions i hear 1.Q, 2.U, 3.E, 4.S    (Q U E S T I O N S )    instead the text

**Comment by raisonhentry** [comment]
pls help issues

**Comment by georpan** [comment]
I had made a mistake in the code with the answers. it's OK

**Comment by akersh-s** [comment]
Closing since it looks like it's been resolved.
