### ISSUE TITLE
Does not keep proper Score

### ISSUE THREAD

**Issue by radmoose** [alexa/skill-sample-nodejs-trivia#3]
I haven't completely figured out why this is happening (although it looks like a logic problem with storing and retrieving the Score info.)

_The other two issues ( #1 and #2 ) I submitted need to be fixed before working on this issue._
(all line numbers are to initial commit)

Line 311  `'score': 0,`
Line 402 `var currentScore = parseInt(this.attributes.score);`
Line 407  `this.attributes['score']++;`
Line 420  `speechOutput += speechOutputAnalysis + "You got " + currentScore.toString() + " out of "`
Line 437 `speechOutput += speechOutputAnalysis + "Your score is " + currentScore.toString() + ". " + repromptText;`
Line 445 `"score": currentScore,`

Sets Score attribute to 0
Gets the Score attribute and sets currentScore
Increments the Score attribute directly however currentScore is never incremented
Plays currentStore (which has never been incremented)
Stores currentScore into Score attribute overwriting the incremented value.

It seems line 407 should be `currentScore++;`

As my GIT skills are relatively non-existent, I am sorry about using issues to suggest my code update.

**Comment by rstarks** [comment]
The score is still not being recorded correctly.

**Comment by mohsinkar** [comment]
@rstarks  it is keeping the correct score, one thing i noticed is that lot of times user just tries to say the number and adding this line "AnswerIntent {Answer}" in the Sample Utterances might help

**Comment by summerellis** [comment]
I followed all of the instructions to a tee yet it's still saying "your score is 0" when a correct answer is entered. Does anyone have any other input on a fix for this?

**Comment by mehtabr** [comment]
I have made those changes in the code and changed the answer intent. it is still not keeping score correctly. Keeps telling me that the score is 0.

**Comment by jcarrico** [comment]
Downloaded and tried today; received same “Your Score is 0” after answering questions correctly. 

Was there any updates on this?

**Comment by mehtabr** [comment]
Hello,

Yes I was able to figure this out. Thanks.

**Comment by jcarrico** [comment]
Can you share the fix as I have everything working properly with exception to the score functioning. I can go through the entire game answering correct but just get "Your score is 0."

Thanks in advance

**Comment by rpop67** [comment]
same problem. Score is not incrementing. Any updates?

**Comment by jcarrico** [comment]
If you've applied the fixes herein, there is one more that I submitted an issue for: https://github.com/alexa/skill-sample-nodejs-trivia/issues/65

That solved it for me!

**Comment by rpop67** [comment]
I have followed a step by step procedure and concluded that neither of the conditions is satisfied. ..
(answerSlotValid
    && parseInt(intent.slots.Answer.value, 10) === sessionAttributes.correctAnswerIndex)

and hence currentScore is not incrementing. Can you focus on this part and help me resolve this issue please. Thank you in advance.

**Comment by Raycon983** [comment]
same problem here...

**Comment by neurogirl47** [comment]
Who closed this issue? It is not fixed. I tried to apply fix #65 by @jcarrico but AnswerIntent function is not on Line 287. I am having trouble applying this fix. Was anyone else able to duplicate this resolution?
