### ISSUE TITLE
AWS Lambda failed to run

### ISSUE THREAD

**Issue by polyren** [alexa/skill-sample-nodejs-trivia#32]
I followed the second and third step, however, Lambda told me that my code is wrong, which comes from your github, any solutions?

{
  "errorMessage": "Cannot find module './question'",
  "errorType": "Error",
  "stackTrace": [
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/index.js:16:19)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)"
  ]
}

**Comment by AnushPatel** [comment]
I have the same error too! I will try to debug the code and I will get back to you. (BTW I am not the creator of the code)

**Comment by polyren** [comment]
I just created a new blueprint and followed the tutorial here
https://10xnation.com/blog/voice-control-iot-devices-alexa-voice-service/
Now it's working well with my lot and Alexa skills kit.
I will close this question
