### ISSUE TITLE
AWS Lambda Error (Could not find ./Question)

### ISSUE THREAD

**Issue by AnushPatel** [alexa/skill-sample-nodejs-trivia#33]
This is the error I am recieving ;
{
"errorMessage": "Cannot find module './question'",
"errorType": "Error",
"stackTrace": [
"require (internal/module.js:20:19)",
"Object. (/var/task/index.js:16:19)",
"Module._compile (module.js:570:32)",
"Object.Module._extensions..js (module.js:579:10)",
"Module.load (module.js:487:32)",
"tryModuleLoad (module.js:446:12)",
"Function.Module._load (module.js:438:3)"
]
}

**Comment by JennJin** [comment]
Did you upload the questions.js file that's in the l[ambda/custom](https://github.com/alexa/skill-sample-nodejs-trivia/tree/en-US/lambda/custom) folder?

**Comment by AnushPatel** [comment]
I believe I did, I have since now got a new error of finding 'Alexa-sdk' but thats because of the outdated instructions for node.js but thanks for the suggestion!
