### ISSUE TITLE
Category "TRIVIA" is out of date with valid categories 

### ISSUE THREAD

**Issue by NealWalters** [alexa/skill-sample-nodejs-trivia#35]
In skill.json change 
      "category": "TRIVIA",
to
      "category": "KNOWLEDGE_AND_TRIVIA",

in order to avoid this error: 

$ ask deploy
-------------------- Create Skill Project --------------------
Profile for the deployment: [default]
  |  Creating new skill...Call create-skill error.
Error code: 400
{
  "message": "The skill manifest is not valid.",
  "violations": [
    {
      "message": "Invalid category."
    }
  ]
}
Valid categories now: https://developer.amazon.com/docs/smapi/skill-manifest.html#category-enum 

Also, the instructions (readme.md) I think need to be updated.  Instead of cd /lambda, it needs to be cd /lambda/custom.  Then before doing the "ask deploy" you need to go up two levels cd ../..  (has to be in the folder where skills.json exists). 

This is the first time I saw "ask cli", very cool!

**Comment by SleepyDeveloper** [comment]
Thanks for pointing this out!!! We can update this but feel free to fork and create a pull request with the changes. We’ll happily merge it in. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NealWalters** [comment]
Done.  My first small contribution to GitHub!

**Comment by akersh-s** [comment]
Closing, Fixed with PR #48 and #38
