### ISSUE TITLE
"errorMessage": "Cannot assign to read only property '74' of string 'QUESTIONS.1.The 1964 classic Rudolph The Red Nosed Reindeer was filmed in. '",

### ISSUE THREAD

**Issue by NealWalters** [alexa/skill-sample-nodejs-trivia#39]
Thanks for this sample.  I've been adding console.log statements to trace the flow (and could provide that if you would like to add it). 

I'm getting back into JavaScript after some time, and just took my first NodeJS class about 2 months ago, so this is also good for looking up all the statements I don't understand. 

I found one more strange issue, but don't understand at all how the translation is happening. 

To force the error to occur every time you play the game, make this change so that you always get the first five questions (but even then it might throw in a higher question, not sure why). 
        //const rand = Math.floor(Math.random() * index);
        const rand = Math.floor(Math.random() * 5);

Then to see what is happening, I added these console.logs: 
    const translatedQuestions = this.t('QUESTIONS');
    console.log("translatedQuestions"); 
    console.log(translatedQuestions); 

What library or tool is doing the .t translation?  Is it I18Next or something else? A NodeJS feature, or an installed package, or part of the Alexa-SDK? 

And it displays the following. You can see that question #2 about "the 1964 classic" has gone bonkers. 

[ { 'Reindeer have very thick coats, how many hairs per square inch do they have?': [ '13,000', '1,200', '5,000', '700', '1,000', '120,000' ] },
{ 'The 1964 classic Rudolph The Red Nosed Reindeer was filmed in. ': 'QUESTIONS.1.The 1964 classic Rudolph The Red Nosed Reindeer was filmed in. ' },
{ 'Santas reindeer are cared for by one of the Christmas elves, what is his name?': 
[ 'Wunorse Openslae',
'Alabaster Snowball',
'Bushy Evergreen',
'Pepper Minstix' ] },

When it hits the question about "the 1964 classic", it blows up with: 
"Cannot assign to read only property '74' of string 'QUESTIONS.1.The 1964 classic Rudolph The Red Nosed Reindeer was filmed in. '", 

When that happens, it is because the variable "answersCopy" will contain the value "QUESTIONS.1.The 1964 classic Rudolph The Red Nosed Reindeer was filmed in. " instead of the the array of the answers for that question. 

Seems like the punctuation and the space at the end matters.  I changed ? on first question to a period, then it gets same error.  But the question about antlers (boys, girls...) ends with a period and works okay. 

There is a somewhat mysterious comment in the code that says: 
"When editing your questions pay attention to your punctuation. Make sure you use question marks or periods."
But that doesn't really explain why... 

Thanks,
Neal Walters

P.S.  At first it was confusing because I might answer "I don't know" and it would happen to be on that question, and I thought it was a problem with the IDONTKNOW intent or soemthing like that.

**Comment by JakeMKelly** [comment]
There's a good explanation for this [here](https://github.com/alexa/skill-sample-nodejs-trivia/issues/14)

**Comment by akersh-s** [comment]
Closing issue, also see PR #56
