### ISSUE TITLE
Outdated Instructions: There is no deploy.js

### ISSUE THREAD

**Issue by janacm** [alexa/skill-sample-nodejs-trivia#42]
There is no deploy.js file in the specified directory. Does anyone know how I can proceed with the tutorial?

![image](https://user-images.githubusercontent.com/2055312/33384230-71c1a714-d4f3-11e7-80cc-e3815ebcdac9.png)

**Comment by kahlil29** [comment]
same issue. You guys really should update or atleast reply in the issues.

**Comment by ghaddink2** [comment]
same issue :(

**Comment by ghaddink2** [comment]
workaround that worked for me: also do npm install alexa-sdk. Then zip the node-modules folder together with the files in "custom" and upload this as 'Function code"

**Comment by mindblower69** [comment]
@ghaddink2 Could you be a bit more precise to what the workaround ended up being? I'm really new to the Node.js and Alexa scene and I feel like every tutorial I find seem to assume I know something that I don't. 

Update: I think I figured it out! Now I'm pretty much done, but it doesn't seem to accept answers. I see it store my values but Alexa just keeps on telling me to try to say a number between 1 and 4

**Comment by akersh-s** [comment]
fixed with PR #48

**Comment by ksg1t** [comment]
deploy.js is still referenced in step 5 of current instructions.
