### ISSUE TITLE
SSML Audio won't be playing

### ISSUE THREAD

**Issue by baidoct** [alexa/skill-sample-nodejs-trivia#47]
I'm trying to integrate the SSML Audio into the question.js but when I do that, the Skill won't even start. 

Here's how I'm trying to do it:

```
{
  "<audio src='https://s3.amazonaws.com/spotify-audio-files/Macklemore-cant-hold-us.mp3' />": [
   'Song 1',
   'Song 2',
],
},
```

What am I doing wrong?

**Comment by kannansantharam** [comment]
https://stackoverflow.com/questions/47849773/ssml-audio-instead-of-words/47866540#47866540

**Comment by akersh-s** [comment]
Looks like it's answered, you can check our docs or post on the forums if you're curious: https://forums.developer.amazon.com/
