### ISSUE TITLE
Questions structure is problematic

### ISSUE THREAD

**Issue by andyrooc** [alexa/skill-sample-nodejs-trivia#60]
I found the questions structure to be problematic - awkward and unreliable. It depends upon the question being the key to an array of answers. This leads to obfuscated code and unreliable keys (js seems to have issues with long multi-character keys in json)

I changed questions to this...
```
QUESTIONS_EN: [
        {
            q: 'some very interesting question?',
            a: [
                'answer 1',
                'answer 2',
                'answer 3',
                'answer 4',
            ],
        },
]
```
...and changed code to:

`const spokenQuestion = translatedQuestions[gameQuestions[currentQuestionIndex]].q;`
...and
`let answersCopy = translatedQuestions[gameQuestionIndexes[correctAnswerIndex]].a`

...style of coding. I find it easier to read and to understand - important when you're trying to learn about writing a voice app, and not trying to untangle code.

It might be worth considering a change?

**Comment by watersplash8** [comment]
I also found questions structure to be unreliable. Even when you start answering the questions that are part of the demo some of the questions produce an error and you can't continue unless you stop/reopen the skill.

I have a question for you... I couldn't understand the second change that you are referring to.
Is that the code that you changed in index.js?

` const translatedQuestion = translatedQuestions[gameQuestionIndexes[correctAnswerIndex]];`

**Comment by andyrooc** [comment]
Yes. For example, the second line in function populateRoundAnswers is:
```javascript
const answersCopy = translatedQuestions[gameQuestionIndexes[correctAnswerIndex]][Object.keys(translatedQuestions[gameQuestionIndexes[correctAnswerIndex]])[0]].slice();
```
I changed it to:
```javascript
let answersCopy = translatedQuestions[gameQuestionIndexes[correctAnswerIndex]].a;
```
by restructuring the question data. A lot simpler IMHO.

**Comment by akersh-s** [comment]
Nice, feel free to submit a PR --since this is stylistic i'm going to close this issue.
