### ISSUE TITLE
ask deploy returns '[Error] Skill not found' following ASK CLI steps only

### ISSUE THREAD

**Issue by mnwone** [alexa/skill-sample-nodejs-trivia#63]
In the instructions, the Get Started was skipped, and only the Setup w/ ASK CLI steps were followed - please confirm this is correct.

ask deploy returns '[Error] Skill not found'.   Please advise.  Thanks in advance.

C:\git\skill-sample-nodejs-trivia>dir
 Volume in drive C has no label.
 Volume Serial Number is 72F7-9EC5

 Directory of C:\git\skill-sample-nodejs-trivia

03/28/2018  01:16 AM    <DIR>          .
03/28/2018  01:16 AM    <DIR>          ..
03/28/2018  01:16 AM    <DIR>          .ask
03/28/2018  01:16 AM    <DIR>          instructions
03/28/2018  01:16 AM             1,205 interactionModel.json
03/28/2018  01:16 AM    <DIR>          lambda
03/28/2018  01:16 AM             4,750 LICENSE.txt
03/28/2018  01:16 AM    <DIR>          models
03/28/2018  01:16 AM             5,960 Readme.md
03/28/2018  01:41 AM               775 skill.json
               4 File(s)         12,690 bytes
               6 Dir(s)   1,742,798,848 bytes free

C:\git\skill-sample-nodejs-trivia>**ask deploy**
-------------------- Update Skill Project --------------------
**[Error] Skill not found.**

**Comment by campionfellin** [comment]
Do you have AWS credentials set up yet? A similar error happened for me, but following the instructions on [this page](https://developer.amazon.com/docs/smapi/set-up-credentials-for-an-amazon-web-services-account.html) worked for me.

Maybe it would be useful to update the ReadMe to reflect this step?

**Comment by mnwone** [comment]
I did not have AWS credentials set up.  Thank you for the link to the instructions.
