### ISSUE TITLE
Missing "AnswerOnlyIntent" function within index.js

### ISSUE THREAD

**Issue by jcarrico** [alexa/skill-sample-nodejs-trivia#65]
Had issue with Answer Only intent answers resulting in " Your score is 0" after answering the question correctly. Found index.js const triviaStateHandlers does not contain a function for the "AnswerOnlyIntent" Intent.

LN 288 - Needs additional function for "AnswerOnlyIntent" 

Snippet added below "AnswerIntent" function:
`   
 "AnswerOnlyIntent": function () {
        handleUserGuess.call(this, false);
    },
`

This resolved so that an answer only, saying "four", allows for the number to be passed appropriately. Fixed my issue and now score is functioning as desired.

**Comment by neurogirl47** [comment]
AnswerIntent function is not on Line 287. I am having trouble applying this fix.

**Comment by akersh-s** [comment]
Fixed in update. closing.
