### ISSUE TITLE
Link to wrong repository when creating lambda function

### ISSUE THREAD

**Issue by vs4k** [alexa/skill-sample-nodejs-trivia#68]
"Search for the application repository named "alexa-skills-kit-nodejs-factskill". You can find it using the provided search box"

This is the trivia tutorial, and the repository this tutorial refers to is skill-sample-nodejs-trivia

**Comment by sirsa2** [comment]
This needs to be fixed ASAP. Lost a couple of hours because of this until I figured out that there was another repository with "trivia" in the name.

**Comment by akersh-s** [comment]
fixed in PR#10
