### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by tlovett1** [alexa/skill-sample-nodejs-trivia#7]
How does this work for anyone? https://github.com/alexa/skill-sample-nodejs-trivia/blame/master/src/index.js#L14 is including a file that does not exist `question.js`

**Comment by rdgsa** [comment]
This is not working for me yet...but questions.js is in the /src directory.

**Comment by mohsinkar** [comment]
@rdgsa what is not working for you ? I might be able to help you out.

**Comment by akersh-s** [comment]
Should be fixed over a series of PR's that we've made.
