### ISSUE TITLE
requested skills response

### ISSUE THREAD

**Issue by brownbe21** [alexa/skill-sample-nodejs-trivia#78]
I'm getting 'there was a problem with the requested skill's response error" but I do get a json response and an echo display response

**Comment by javaarchive** [comment]
I have the error too
I get
  "errorMessage": "Cannot convert undefined or null to object",
  "errorType": "TypeError",
  "stackTrace": [
    "Object.handleUserGuess (/var/task/index.js:221:39)",
    "Object.AnswerIntent (/var/task/index.js:290:25)",
    "emitNone (events.js:86:13)",
    "AlexaRequestEmitter.emit (events.js:185:7)",
    "AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:216:10)",
    "AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:181:23)",
    "HandleLambdaEvent.i18n.use.init (/var/task/node_modules/alexa-sdk/lib/alexa.js:123:29)",
    "/var/task/node_modules/i18next/dist/commonjs/i18next.js:190:9",
    "done (/var/task/node_modules/i18next/dist/commonjs/i18next.js:281:21)",
    "/var/task/node_modules/i18next/dist/commonjs/i18next.js:302:7"
  ]
}
from the logs

**Comment by akersh-s** [comment]
Please open a post on the forums: https://forums.developer.amazon.com/, thanks
