### ISSUE TITLE
Code for questions is wrong

### ISSUE THREAD

**Issue by grant-musick** [alexa/skill-sample-nodejs-trivia#8]
populateGameQuestions creates garbage because questions.length is undefined.

questions.length is undefined b/c the questions value is not an array but a dictionary of arrays.

My quick hack around this was the following:

const proto_questions = require('./questions');
const questions = proto_questions.QUESTIONS_EN_US;

Which then allows the code to run more or less as expected (at least it doesn't blow up).

Probably ought to wrap the many uses of the "questions" variable in a function so it can support locales (as is implied by the questions code).

**Comment by polomint82** [comment]
Grant, did you ever get this working? I think I'm running into the same issue.

**Comment by akersh-s** [comment]
Closed in PR#8
