### ISSUE TITLE
Repository button

### ISSUE THREAD

**Issue by repath** [alexa/skill-sample-nodejs-trivia#80]
Dear Team,
"Click on the **repository**. This repository will create the Lambda function, add Alexa Skills Kit as it's trigger, and sets up an IAM role for you. It will also add the code from this GitHub repo and include it's dependencies to your Lambda function so that you don't have to upload it yourself."

the above text is as written in the web page, I could not find any REPOSITORY button to click,.
can you please help.

with regards
repath athyala.

**Comment by akersh-s** [comment]
User error, closing this issue -- if it persists please open an issue here: https://forums.developer.amazon.com/
