### ISSUE TITLE
Issue with the answers

### ISSUE THREAD

**Issue by Raycon983** [alexa/skill-sample-nodejs-trivia#82]
I had a issue with Answer Only intent, all my answers resulting in " Your score is 0" after answering the question correctly.
I tried many things, but the result is the same for all my answers.
I'm using the exact model here and "alexa-skills-kit-nodejs-triviaskill — Version 2.0.2" on the serverless option in AWS Lambda".
language = en-US

**Comment by dancadana** [comment]
Why is this issue closed? I'm still getting the same problem. I'm typing in the simulator corret answer number and it sends DontKnowIntent.

**Comment by Raycon983** [comment]
> Why is this issue closed? I'm still getting the same problem. I'm typing in the simulator corret answer number and it sends DontKnowIntent.

Try writing the option number with letters, ex: one, two,three, etc.
