### ISSUE TITLE
Using template error(Code is unmodified from original)

### ISSUE THREAD

**Issue by javaarchive** [alexa/skill-sample-nodejs-trivia#85]
When I use the template i get the following error
{ 
 "errorMessage": "Cannot convert undefined or null to object",
  "errorType": "TypeError",
  "stackTrace": [
    "Object.handleUserGuess (/var/task/index.js:221:39)",
    "Object.AnswerIntent (/var/task/index.js:290:25)",
    "emitNone (events.js:86:13)",
    "AlexaRequestEmitter.emit (events.js:185:7)",
    "AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:216:10)",
    "AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:181:23)",
    "HandleLambdaEvent.i18n.use.init (/var/task/node_modules/alexa-sdk/lib/alexa.js:123:29)",
    "/var/task/node_modules/i18next/dist/commonjs/i18next.js:190:9",
    "done (/var/task/node_modules/i18next/dist/commonjs/i18next.js:281:21)",
    "/var/task/node_modules/i18next/dist/commonjs/i18next.js:302:7"
  ]

}
I used the second option after blank in aws lambda.

**Comment by akersh-s** [comment]
Looks like User error, closing this issue.
