### ISSUE TITLE
Interpreting German Numbers

### ISSUE THREAD

**Issue by aaronredmond** [alexa/skill-sample-nodejs-trivia#87]
In the US English version of the skill when a user answers "one", "two", etc. the value is converted to the numeric equivalent "1", "2", etc. and then processed correctly via the "isAnswerSlotValid" function. 

However in German when a user answers "eine", "zwei", etc. the value in not converted and therefore not processed correctly via the" isAnswerSlotValid" function, so even when the correct answer is specified the answer is flagged as incorrect.

**Comment by akersh-s** [comment]
Should work as expected now. Closing.
