### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by avogabo** [alexa/skill-sample-nodejs-trivia#90]
Its possible translate this skill mode to spanish?

**Comment by AlexaforMuggles** [comment]
It should be. You would just include one or both of these: 

es-ES | Spanish (ES)
es-MX | Spanish (MX)

You could just replace de-DE with the Spanish version you want and then replace the data inside.

**Comment by akersh-s** [comment]
Closing this issue: for future questions please check the developer forums: https://forums.developer.amazon.com/
